// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_3Mum_gtAYWx4eRs5At4IkVhRYS1sCp0',
    appId: '1:371235505096:web:08b9fbb89a15db7575f6fd',
    messagingSenderId: '371235505096',
    projectId: 'flash-chat-37010',
    authDomain: 'flash-chat-37010.firebaseapp.com',
    storageBucket: 'flash-chat-37010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjYG27o14PpocebuX9BPA7WvdW8MMtEuk',
    appId: '1:371235505096:android:e720f3cd1ba48ced75f6fd',
    messagingSenderId: '371235505096',
    projectId: 'flash-chat-37010',
    storageBucket: 'flash-chat-37010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-ljGNShdG6MJYYeRkJoidUpFQkzpKyE',
    appId: '1:371235505096:ios:8fb1bd0ab44c287775f6fd',
    messagingSenderId: '371235505096',
    projectId: 'flash-chat-37010',
    storageBucket: 'flash-chat-37010.appspot.com',
    iosClientId: '371235505096-h86g4iqlkven2ffgqc9klgvleq5ab7kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchatnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-ljGNShdG6MJYYeRkJoidUpFQkzpKyE',
    appId: '1:371235505096:ios:8fb1bd0ab44c287775f6fd',
    messagingSenderId: '371235505096',
    projectId: 'flash-chat-37010',
    storageBucket: 'flash-chat-37010.appspot.com',
    iosClientId: '371235505096-h86g4iqlkven2ffgqc9klgvleq5ab7kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchatnew',
  );
}
